using AnimeTracker.Api.Models.Entities;
using Microsoft.EntityFrameworkCore;

namespace AnimeTracker.Api.Data;

public class AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
{
    public DbSet<AnimeCache> AnimeCaches => Set<AnimeCache>();
    public DbSet<WatchEntry> WatchEntries => Set<WatchEntry>();
    public DbSet<Tag> Tags => Set<Tag>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AnimeCache>(entity =>
        {
            entity.HasKey(a => a.AniListId);
            // AniList assigns the id, so it's never generated by the database.
            entity.Property(a => a.AniListId).ValueGeneratedNever();
            entity.Property(a => a.TitleRomaji).IsRequired();
        });

        modelBuilder.Entity<WatchEntry>(entity =>
        {
            entity.HasOne(w => w.Anime)
                .WithMany(a => a.WatchEntries)
                .HasForeignKey(w => w.AniListId)
                .OnDelete(DeleteBehavior.Restrict);

            entity.HasIndex(w => w.Status);
            entity.HasIndex(w => w.AniListId);

            // Implicit many-to-many; EF Core creates and manages the "WatchEntryTag" join table.
            entity.HasMany(w => w.Tags)
                .WithMany(t => t.WatchEntries)
                .UsingEntity(j => j.ToTable("WatchEntryTag"));
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasIndex(t => t.Name).IsUnique();
        });
    }
}
